releases:
  - name: elasticache-broker
    version: 0.0.1512581033
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/elasticache-broker-0.0.1512581033.tgz
    sha1: ca5339301dd0ffb4478289f37cd692898bad463d

jobs:
  - name: elasticache_broker
    azs: [z1, z2]
    instances: 2
    vm_type: elasticache_broker
    stemcell: default
    templates:
      - name: elasticache-broker
        release: elasticache-broker
    networks:
      - name: cf
    properties:
      elasticache-broker:
        log_level: DEBUG
        broker_name: "elasticache-broker"
        broker_username: "elasticache-broker"
        broker_password: (( grab secrets.elasticache_broker_admin_password ))
        auth_token_seed: (( grab secrets.elasticache_broker_auth_token_seed ))
        region: "eu-west-1"
        cache_subnet_group_name: (( grab terraform_outputs.elasticache_broker_subnet_group_name ))
        vpc_security_group_ids:
        - (( grab terraform_outputs.elasticache_broker_instances_security_group_id ))

        catalog:
          services:
            - id: 7b94ab02-478f-4c1b-95d8-21522672930b
              name: redis
              description: AWS ElastiCache Redis service
              metadata:
                displayName: Redis
                imageUrl: https://redis.io/images/redis-white.png
                longDescription: AWS ElastiCache Redis cluster
                providerDisplayName: GOV.UK PaaS
                documentationUrl: https://docs.cloud.service.gov.uk/#redis
                supportUrl: https://www.cloud.service.gov.uk/support.html
              tags:
                - elasticache
                - redis
              bindable: true
              plan_updateable: false
              plans:
                - id: 3a51701c-eef3-447c-882b-907ad2bcb7ab
                  name: tiny
                  description: 568MB RAM, 1 shard, single node, no backups, no failover
                  free: true
                  metadata:
                    displayName: Redis Tiny

        plan_configs:
          3a51701c-eef3-447c-882b-907ad2bcb7ab:
            instance_type: cache.t2.micro
            replicas_per_node_group: 0
            shard_count: 1
            snapshot_retention_limit: 0
            automatic_failover_enabled: false
            parameters:
              maxmemory-policy: volatile-lru
              reserved-memory: '0'

properties:
  cc:
    security_group_definitions:
      - name: elasticache_broker_instances
        rules:
          - protocol: tcp
            destination: (( grab terraform_outputs.aws_backing_service_cidr_all ))
            ports: '6379'

    default_running_security_groups:
      - (( append ))
      - "elasticache_broker_instances"
    default_staging_security_groups:
      - (( append ))
      - "elasticache_broker_instances"
