# FIXME: Copied from cf-deployment experimental opsfile in the latest
# version of cf-deployment
#
# https://github.com/cloudfoundry/cf-deployment/blob/v1.31.0/operations/experimental/use-log-cache.yml
#
# Replace for the upstream opsfile once we upgrade cf-deployment > v1.31.0
#
- type: replace
  path: /releases/-
  value:
    name: log-cache
    sha: 87134510c23ce5facca665ac025f41a19340f5e9
    url: https://bosh.io/d/github.com/cloudfoundry/log-cache-release?v=1.1.1
    version: 1.1.1

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    name: log-cache
    properties:
      egress_port: 8080
      health_addr: localhost:6060
      tls:
        ca_cert: ((log_cache.ca))
        cert: ((log_cache.certificate))
        key: ((log_cache.private_key))
    release: log-cache

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    name: log-cache-gateway
    properties:
      gateway_addr: localhost:8081
    release: log-cache

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    name: log-cache-group-reader
    properties:
      port: 8084
    release: log-cache

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    consumes:
      reverse_log_proxy:
        from: reverse_log_proxy
    name: log-cache-nozzle
    properties:
      logs_provider:
        tls:
          ca_cert: ((logs_provider.ca))
          cert: ((logs_provider.certificate))
          key: ((logs_provider.private_key))
    release: log-cache

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    name: log-cache-expvar-forwarder
    properties:
      counters:
      - addr: http://localhost:6060/debug/vars
        name: egress
        source_id: log-cache
        template: '{{.LogCache.Egress}}'
      - addr: http://localhost:6060/debug/vars
        name: ingress
        source_id: log-cache
        template: '{{.LogCache.Ingress}}'
      - addr: http://localhost:6060/debug/vars
        name: expired
        source_id: log-cache
        template: '{{.LogCache.Expired}}'
      - addr: http://localhost:6061/debug/vars
        name: egress
        source_id: log-cache-nozzle
        template: '{{.Nozzle.Egress}}'
      - addr: http://localhost:6061/debug/vars
        name: ingress
        source_id: log-cache-nozzle
        template: '{{.Nozzle.Ingress}}'
      - addr: http://localhost:6061/debug/vars
        name: err
        source_id: log-cache-nozzle
        template: '{{.Nozzle.Err}}'
      gauges:
      - addr: http://localhost:6060/debug/vars
        name: cache-period
        source_id: log-cache
        template: '{{.LogCache.CachePeriod}}'
      - addr: http://localhost:6060/debug/vars
        name: store-size
        source_id: log-cache
        template: '{{.LogCache.StoreSize}}'
      - addr: http://localhost:6060/debug/vars
        name: total-system-memory
        source_id: log-cache
        template: '{{.LogCache.TotalSystemMemory}}'
      - addr: http://localhost:6060/debug/vars
        name: available-system-memory
        source_id: log-cache
        template: '{{.LogCache.AvailableSystemMemory}}'
    release: log-cache

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    name: route_registrar
    properties:
      route_registrar:
        routes:
        - name: log-cache-reverse-proxy
          port: 8083
          registration_interval: 20s
          uris:
          - log-cache.((system_domain))
          - '*.log-cache.((system_domain))'
    release: routing

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    name: log-cache-cf-auth-proxy
    properties:
      cc:
        common_name: cloud-controller-ng.service.cf.internal
        ca_cert: ((log_cache_tls_cc_auth_proxy.ca))
        cert: ((log_cache_tls_cc_auth_proxy.certificate))
        key: ((log_cache_tls_cc_auth_proxy.private_key))
      proxy_port: 8083
      uaa:
        ca_cert: ((uaa_ca.certificate))
        client_id: doppler
        client_secret: ((uaa_clients_doppler_secret))
        internal_addr: https://uaa.service.cf.internal:8443
    release: log-cache

- type: replace
  path: /variables/-
  value:
    name: logs_provider
    options:
      ca: loggregator_ca
      common_name: log-cache
      extended_key_usage:
      - client_auth
      - server_auth
    type: certificate
- type: replace
  path: /variables/-
  value:
    name: log_cache_ca
    options:
      common_name: log-cache
      is_ca: true
    type: certificate
- type: replace
  path: /variables/-
  value:
    name: log_cache
    options:
      alternative_names:
      - log_cache
      - log-cache
      - logcache
      ca: log_cache_ca
      common_name: log-cache
      extended_key_usage:
      - client_auth
      - server_auth
    type: certificate
- type: replace
  path: /variables/-
  value:
    name: log_cache_tls_cc_auth_proxy
    options:
      ca: service_cf_internal_ca
      common_name: log-cache
      extended_key_usage:
      - client_auth
    type: certificate
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=log-cache-scheduler?
  value:
    name: log-cache-scheduler
    release: log-cache

# FIXME: the log-cache release relies on bosh-dns https://github.com/cloudfoundry/bosh-dns-release
# to discover the reverse-log-proxy address, but we don not use bosh-dns yet.
#
# We override the link information with the consul dns name and hardcoded port
- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-nozzle/consumes/reverse_log_proxy
  value:
    address: reverse-log-proxy.service.cf.internal
    instances: []
    properties:
      reverse_log_proxy:
        egress:
          port: 8082

- type: replace
  path: /instance_groups/name=doppler/jobs/name=log-cache-cf-auth-proxy/consumes?/cloud_controller?
  value:
    address: cloud-controller-ng.service.cf.internal
    instances: []
